# Generated by Django 3.0.5 on 2021-03-04 14:27

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('location_text', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('question', models.CharField(max_length=256)),
                ('answer_type', models.CharField(choices=[('int', 'Scale'), ('text', 'Text'), ('bool', 'True/False')], default='bool', max_length=4)),
                ('symptom_type', models.CharField(choices=[('MOP', 'Member of public'), ('HCW', 'Health care worker'), ('EOV', 'Entomologist/vet')], default='MOP', max_length=4)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='symptoms')),
            ],
            options={
                'ordering': ('symptom_type', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, max_length=2056, null=True)),
                ('scale_response', models.IntegerField(null=True)),
                ('bool_response', models.BooleanField(null=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleep_app.Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleep_app.Person')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleep_app.Response')),
            ],
        ),
    ]
